### 1.1 Pulizia e Preparazione dei Dati
In questa fase verifichiamo la presenza di valori nulli, duplicati o anomalie strutturali.
Un dataset pulito è il prerequisito per conclusioni affidabili.
Identifichiamo inoltre il numero di utenti unici e la distribuzione iniziale delle categorie.

In [42]:
import pandas as pd

# df = favs.merge(details, how='left', on='mal_id')
favs = pd.read_csv("../data/favs.csv")
character_anime_works = pd.read_csv("../data/character_anime_works.csv")
character_nicknames = pd.read_csv("../data/character_nicknames.csv")
characters = pd.read_csv("../data/characters.csv")

In [40]:
# Drop rows non utili
favs = favs.dropna(subset=['username'])
favs

            username   fav_type      id
0          ishikawas      anime   45649
1          ishikawas      anime   38680
2          ishikawas      anime     795
3          ishikawas      anime   37510
4          ishikawas      anime     820
...              ...        ...     ...
4178742  vincent0607  character     497
4178743  vincent0607  character  118739
4178744  vincent0607  character  188177
4178745  vincent0607  character  141354
4178746  vincent0607  character  195178

[4178743 rows x 3 columns]

In [60]:
# Eliminare doppioni su tutti i csv

# Per riga
#print(f"Numero di righe duplicate: {favs.duplicated().sum()}")
#print(f"Numero di righe duplicate: {character_anime_works.duplicated().sum()}")
#print(f"Numero di righe duplicate: {character_nicknames.duplicated().sum()}")
print(f"Numero di righe duplicate: {characters.duplicated().sum()}")

Numero di righe duplicate: 455

In [57]:
# # keep=False mostra tutte le occorrenze del duplicato, non solo la seconda
duplicati = characters[characters.duplicated(keep=False)]
duplicati

,character_mal_id,url,name,name_kanji,image,favorites,about
853,279200.0,https://myanimelist.net/character/279200/Shing...,Shingo Shimazaki,島崎 真悟,https://cdn.myanimelist.net/images/characters/...,1.0,NaN
854,279200.0,https://myanimelist.net/character/279200/Shing...,Shingo Shimazaki,島崎 真悟,https://cdn.myanimelist.net/images/characters/...,1.0,NaN
909,279142.0,https://myanimelist.net/character/279142/Kaho,Kaho,NaN,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
910,279142.0,https://myanimelist.net/character/279142/Kaho,Kaho,NaN,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
1166,278865.0,https://myanimelist.net/character/278865/Yoshi...,Yoshirou Sonozaki,園崎 義郎,https://cdn.myanimelist.net/images/characters/...,0.0,The owner of the restaurant Angel Mort.
...,...,...,...,...,...,...,...
209789,282042.0,https://myanimelist.net/character/282042/Alina,Alina,アリナ,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
209849,282115.0,https://myanimelist.net/character/282115/Cavitt,Cavitt,キャビット,https://cdn.myanimelist.net/images/characters/...,0.0,Lieutenant Rencon's younger sister.\n\nNo voic...
209850,282115.0,https://myanimelist.net/character/282115/Cavitt,Cavitt,キャビット,https://cdn.myanimelist.net/images/characters/...,0.0,Lieutenant Rencon's younger sister.\n\nNo voic...
209858,282131.0,https://myanimelist.net/character/282131/Lieut...,Lieutenant Rencon,レンコン中尉,https://cdn.myanimelist.net/images/characters/...,0.0,Former lieutenant of Mar Expedition and older ...
209859,282131.0,https://myanimelist.net/character/282131/Lieut...,Lieutenant Rencon,レンコン中尉,https://cdn.myanimelist.net/images/characters/...,0.0,Former lieutenant of Mar Expedition and older ...

In [68]:
# Controllo duplicati su ID specifici
duplicati_id = characters.duplicated(subset=['character_mal_id']).sum()
print(f"ID duplicati: {duplicati_id}")

ID duplicati: 0

In [67]:
characters = characters.drop_duplicates(subset=['character_mal_id'], keep="first")
characters

,character_mal_id,url,name,name_kanji,image,favorites,about
0,280386.0,https://myanimelist.net/character/280386/Envi_...,Envi Mel Champagne,エンヴィ・メル・シャンパーニュ,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
1,280354.0,https://myanimelist.net/character/280354/Eleven,Eleven,イレヴン,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
2,280353.0,https://myanimelist.net/character/280353/Stud,Stud,スタッド,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
3,280352.0,https://myanimelist.net/character/280352/Judge,Judge,ジャッジ,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
4,280339.0,https://myanimelist.net/character/280339/Eiji_...,Eiji Kurokawa,黒川 英治,https://cdn.myanimelist.net/img/sp/icon/apple-...,0.0,NaN
...,...,...,...,...,...,...,...
209958,282276.0,https://myanimelist.net/character/282276/Farra...,Farrah Van Dorothy,ファラ・ヴァン・ドロシー,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
209959,282277.0,https://myanimelist.net/character/282277/Harri...,Harris Mead,ハリス・ミード,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
209960,282278.0,https://myanimelist.net/character/282278/Rob,Rob,ロブ,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
209961,282281.0,https://myanimelist.net/character/282281/Grimm,Grimm,グリム,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
209962,282284.0,https://myanimelist.net/character/282284/Joel_...,Joel Widdison,ジョエル,https://cdn.myanimelist.net/images/characters/...,0.0,NaN

In [ ]:
character_nicknames = character_nicknames.dropna(subset=['nickname'])
character_nicknames

In [51]:
characters = characters.dropna(subset=['name'])
characters

,character_mal_id,url,name,name_kanji,image,favorites,about
0,280386.0,https://myanimelist.net/character/280386/Envi_...,Envi Mel Champagne,エンヴィ・メル・シャンパーニュ,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
1,280354.0,https://myanimelist.net/character/280354/Eleven,Eleven,イレヴン,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
2,280353.0,https://myanimelist.net/character/280353/Stud,Stud,スタッド,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
3,280352.0,https://myanimelist.net/character/280352/Judge,Judge,ジャッジ,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
4,280339.0,https://myanimelist.net/character/280339/Eiji_...,Eiji Kurokawa,黒川 英治,https://cdn.myanimelist.net/img/sp/icon/apple-...,0.0,NaN
...,...,...,...,...,...,...,...
209958,282276.0,https://myanimelist.net/character/282276/Farra...,Farrah Van Dorothy,ファラ・ヴァン・ドロシー,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
209959,282277.0,https://myanimelist.net/character/282277/Harri...,Harris Mead,ハリス・ミード,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
209960,282278.0,https://myanimelist.net/character/282278/Rob,Rob,ロブ,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
209961,282281.0,https://myanimelist.net/character/282281/Grimm,Grimm,グリム,https://cdn.myanimelist.net/images/characters/...,0.0,NaN
209962,282284.0,https://myanimelist.net/character/282284/Joel_...,Joel Widdison,ジョエル,https://cdn.myanimelist.net/images/characters/...,0.0,NaN

In [ ]:
characters