## 1.1 Cleaning and Data Preparation

In this phase we check for null values, duplicates, or structural anomalies to delete it and improve the dataset of `favs`, `character_anime_works`, `character_nicknames`
and `characters`.
<br>We also identify the number of unique users and the intial distribution of categories.

---

### Loading Data from csv files

In [1]:
from lib.dbconnection import create_db_engine
import lib.readSaveCsv as rsc

engine = create_db_engine()

# df = favs.merge(details, how='left', on='mal_id')
favs = rsc.load_csv_file(engine, "favs")
character_anime_works = rsc.load_csv_file(engine, "character_anime_works")
character_nicknames = rsc.load_csv_file(engine, "character_nicknames")
characters = rsc.load_csv_file(engine, "characters")

Successo: Dati letti correttamente.
Successo: Dati letti correttamente.
Successo: Dati letti correttamente.
Successo: Dati letti correttamente.

---

### Checking DataFrames info and visualise first rows

In [2]:
favs.info()
print('\n')
character_anime_works.info()
print('\n')
character_nicknames.info()
print('\n')
characters.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4178747 entries, 0 to 4178746
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   username  object
 1   fav_type  object
 2   id        object
dtypes: object(3)
memory usage: 95.6+ MB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236816 entries, 0 to 236815
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   anime_mal_id      236816 non-null  int64
 1   character_mal_id  236816 non-null  int64
 2   character_name    236816 non-null  object
 3   role              236816 non-null  object
dtypes: int64(2), object(2)
memory usage: 7.2+ MB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37080 entries, 0 to 37079
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   character_mal_id  37080 non-null  int64
 1   nickname          37064 non-null  object
dtypes: int64(1), object(1)
memory usage: 579.5+ KB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209963 entries, 0 to 209962
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   character_mal_id  209961 non-null  float64
 1   url               209961 non-null  object
 2   name              209961 non-null  object
 3   name_kanji        154483 non-null  object
 4   image             209961 non-null  object
 5   favorites         209961 non-null  object
 6   about             112987 non-null  object
dtypes: float64(1), object(6)
memory usage: 11.2+ MB

In [3]:
favs

            username   fav_type      id
0          ishikawas      anime   45649
1          ishikawas      anime   38680
2          ishikawas      anime     795
3          ishikawas      anime   37510
4          ishikawas      anime     820
...              ...        ...     ...
4178742  vincent0607  character     497
4178743  vincent0607  character  118739
4178744  vincent0607  character  188177
4178745  vincent0607  character  141354
4178746  vincent0607  character  195178

[4178747 rows x 3 columns]

In [4]:
character_anime_works

        anime_mal_id  character_mal_id    character_name        role
0               2928              5781             Atoli        Main
1               2928                33             Haseo        Main
2               2928                32              Ovan        Main
3               2928                34             Shino        Main
4               2928              5785              Aina  Supporting
...              ...               ...               ...         ...
236811         31245            137157    Shibasaki, Ken  Supporting
236812         36305            136064  Hamanaka, Midori        Main
236813         36305            133916      Narumi, Sena        Main
236814         36305            124942   Hayasaka, Akari  Supporting
236815         34895            155887  Shiraha, Setsuna        Main

[236816 rows x 4 columns]

In [5]:
character_nicknames

       character_mal_id              nickname
0                280205              Hikaruko
1                280129              Hinacchi
2                280127         Bertha Willis
3                280066                 Jimmy
4                280059  Full Body Red Square
...                 ...                   ...
37075            282159             Ling Long
37076            282159            Silvermoon
37077            282227          Mei's Mother
37078            282254                Cyrano
37079            282255                 Lacey

[37080 rows x 2 columns]

In [6]:
characters

,character_mal_id,url,name,name_kanji,image,favorites,about
0,280386.0,https://myanimelist.net/character/280386/Envi_...,Envi Mel Champagne,エンヴィ・メル・シャンパーニュ,https://cdn.myanimelist.net/images/characters/...,0,None
1,280354.0,https://myanimelist.net/character/280354/Eleven,Eleven,イレヴン,https://cdn.myanimelist.net/images/characters/...,0,None
2,280353.0,https://myanimelist.net/character/280353/Stud,Stud,スタッド,https://cdn.myanimelist.net/images/characters/...,0,None
3,280352.0,https://myanimelist.net/character/280352/Judge,Judge,ジャッジ,https://cdn.myanimelist.net/images/characters/...,0,None
4,280339.0,https://myanimelist.net/character/280339/Eiji_...,Eiji Kurokawa,黒川 英治,https://cdn.myanimelist.net/img/sp/icon/apple-...,0,None
...,...,...,...,...,...,...,...
209958,282276.0,https://myanimelist.net/character/282276/Farra...,Farrah Van Dorothy,ファラ・ヴァン・ドロシー,https://cdn.myanimelist.net/images/characters/...,0.0,None
209959,282277.0,https://myanimelist.net/character/282277/Harri...,Harris Mead,ハリス・ミード,https://cdn.myanimelist.net/images/characters/...,0.0,None
209960,282278.0,https://myanimelist.net/character/282278/Rob,Rob,ロブ,https://cdn.myanimelist.net/images/characters/...,0.0,None
209961,282281.0,https://myanimelist.net/character/282281/Grimm,Grimm,グリム,https://cdn.myanimelist.net/images/characters/...,0.0,None
209962,282284.0,https://myanimelist.net/character/282284/Joel_...,Joel Widdison,ジョエル,https://cdn.myanimelist.net/images/characters/...,0.0,None

### `null` values detection and removal

P.S.: character_anime_works doesn't have null values

In [7]:
favs = favs.dropna(subset=['username'])
favs

            username   fav_type      id
0          ishikawas      anime   45649
1          ishikawas      anime   38680
2          ishikawas      anime     795
3          ishikawas      anime   37510
4          ishikawas      anime     820
...              ...        ...     ...
4178742  vincent0607  character     497
4178743  vincent0607  character  118739
4178744  vincent0607  character  188177
4178745  vincent0607  character  141354
4178746  vincent0607  character  195178

[4178743 rows x 3 columns]

In [8]:
character_nicknames = character_nicknames.dropna(subset=['nickname'])
character_nicknames

       character_mal_id              nickname
0                280205              Hikaruko
1                280129              Hinacchi
2                280127         Bertha Willis
3                280066                 Jimmy
4                280059  Full Body Red Square
...                 ...                   ...
37075            282159             Ling Long
37076            282159            Silvermoon
37077            282227          Mei's Mother
37078            282254                Cyrano
37079            282255                 Lacey

[37064 rows x 2 columns]

In [9]:
characters = characters.dropna(subset=['name'])
characters

,character_mal_id,url,name,name_kanji,image,favorites,about
0,280386.0,https://myanimelist.net/character/280386/Envi_...,Envi Mel Champagne,エンヴィ・メル・シャンパーニュ,https://cdn.myanimelist.net/images/characters/...,0,None
1,280354.0,https://myanimelist.net/character/280354/Eleven,Eleven,イレヴン,https://cdn.myanimelist.net/images/characters/...,0,None
2,280353.0,https://myanimelist.net/character/280353/Stud,Stud,スタッド,https://cdn.myanimelist.net/images/characters/...,0,None
3,280352.0,https://myanimelist.net/character/280352/Judge,Judge,ジャッジ,https://cdn.myanimelist.net/images/characters/...,0,None
4,280339.0,https://myanimelist.net/character/280339/Eiji_...,Eiji Kurokawa,黒川 英治,https://cdn.myanimelist.net/img/sp/icon/apple-...,0,None
...,...,...,...,...,...,...,...
209958,282276.0,https://myanimelist.net/character/282276/Farra...,Farrah Van Dorothy,ファラ・ヴァン・ドロシー,https://cdn.myanimelist.net/images/characters/...,0.0,None
209959,282277.0,https://myanimelist.net/character/282277/Harri...,Harris Mead,ハリス・ミード,https://cdn.myanimelist.net/images/characters/...,0.0,None
209960,282278.0,https://myanimelist.net/character/282278/Rob,Rob,ロブ,https://cdn.myanimelist.net/images/characters/...,0.0,None
209961,282281.0,https://myanimelist.net/character/282281/Grimm,Grimm,グリム,https://cdn.myanimelist.net/images/characters/...,0.0,None
209962,282284.0,https://myanimelist.net/character/282284/Joel_...,Joel Widdison,ジョエル,https://cdn.myanimelist.net/images/characters/...,0.0,None

### Duplicate rows detection and removal

In [10]:
print(f"Number of rows duplicated (favs): {favs.duplicated().sum()}\n")
print(f"Number of rows duplicated (character_anime_works): {character_anime_works.duplicated().sum()}\n")
print(f"Number of rows duplicated (character_nicknames): {character_nicknames.duplicated().sum()}\n")
print(f"Number of rows duplicated (characters): {characters.duplicated().sum()}")

Number of rows duplicated (favs): 0

Number of rows duplicated (character_anime_works): 0

Number of rows duplicated (character_nicknames): 102

Number of rows duplicated (characters): 455

In [11]:
duplicati = characters[characters.duplicated(keep=False)]
duplicati

,character_mal_id,url,name,name_kanji,image,favorites,about
853,279200.0,https://myanimelist.net/character/279200/Shing...,Shingo Shimazaki,島崎 真悟,https://cdn.myanimelist.net/images/characters/...,1,None
854,279200.0,https://myanimelist.net/character/279200/Shing...,Shingo Shimazaki,島崎 真悟,https://cdn.myanimelist.net/images/characters/...,1,None
909,279142.0,https://myanimelist.net/character/279142/Kaho,Kaho,None,https://cdn.myanimelist.net/images/characters/...,0,None
910,279142.0,https://myanimelist.net/character/279142/Kaho,Kaho,None,https://cdn.myanimelist.net/images/characters/...,0,None
1166,278865.0,https://myanimelist.net/character/278865/Yoshi...,Yoshirou Sonozaki,園崎 義郎,https://cdn.myanimelist.net/images/characters/...,0,The owner of the restaurant Angel Mort.
...,...,...,...,...,...,...,...
209791,282042.0,https://myanimelist.net/character/282042/Alina,Alina,アリナ,https://cdn.myanimelist.net/images/characters/...,0.0,None
209851,282115.0,https://myanimelist.net/character/282115/Cavitt,Cavitt,キャビット,https://cdn.myanimelist.net/images/characters/...,0.0,Lieutenant Rencon's younger sister.\n\nNo voic...
209852,282115.0,https://myanimelist.net/character/282115/Cavitt,Cavitt,キャビット,https://cdn.myanimelist.net/images/characters/...,0.0,Lieutenant Rencon's younger sister.\n\nNo voic...
209860,282131.0,https://myanimelist.net/character/282131/Lieut...,Lieutenant Rencon,レンコン中尉,https://cdn.myanimelist.net/images/characters/...,0.0,Former lieutenant of Mar Expedition and older ...
209861,282131.0,https://myanimelist.net/character/282131/Lieut...,Lieutenant Rencon,レンコン中尉,https://cdn.myanimelist.net/images/characters/...,0.0,Former lieutenant of Mar Expedition and older ...

In [12]:
favs = favs.drop_duplicates(keep="first")
character_anime_works = character_anime_works.drop_duplicates(keep="first")
character_nicknames = character_nicknames.drop_duplicates(keep="first")
characters = characters.drop_duplicates(keep="first")

In [13]:
print(f"Number of rows duplicated (favs): {favs.duplicated().sum()}\n")
print(f"Number of rows duplicated (character_anime_works): {character_anime_works.duplicated().sum()}\n")
print(f"Number of rows duplicated (character_nicknames): {character_nicknames.duplicated().sum()}\n")
print(f"Number of rows duplicated (characters): {characters.duplicated().sum()}")

Number of rows duplicated (favs): 0

Number of rows duplicated (character_anime_works): 0

Number of rows duplicated (character_nicknames): 0

Number of rows duplicated (characters): 0

### Typo correction

In [14]:
favs.dtypes

username    object
fav_type    object
id          object
dtype: object

In [17]:
favs = favs.copy()
characters = characters.copy()

characters.loc[:, 'character_mal_id'] = characters['character_mal_id'].astype('int64')
#characters.loc[:, 'favorites'] = characters['favorites'].astype('int64')

favs.loc[:, 'fav_type'] = favs['fav_type'].astype('category')
character_anime_works.loc[:, 'role'] = character_anime_works['role'].astype('category')

### Saving in cleaned csv files

In [18]:
rsc.save_csv_file(favs, 'favs', engine)
rsc.save_csv_file(character_anime_works, 'character_anime_works', engine)
rsc.save_csv_file(character_nicknames, 'character_nicknames', engine)
rsc.save_csv_file(characters, 'characters', engine)

Successo: 4178743 righe caricate nella tabella 'favs'.
Successo: 236816 righe caricate nella tabella 'character_anime_works'.
Successo: 36962 righe caricate nella tabella 'character_nicknames'.
Successo: 120 righe caricate nella tabella 'characters'.