## 1.1 Cleaning and Data Preparation

In this phase we check for null values, duplicates, or structural anomalies to delete it and improve the dataset of `favs`, `character_anime_works`, `character_nicknames`
and `characters`.
<br>We also identify the number of unique users and the intial distribution of categories.

---

### Loading Data from csv files

In [1]:
from lib.dbconnection import create_db_engine
import lib.readSaveCsv as rsc

engine = create_db_engine()

favs = rsc.import_data(engine, "favs")
character_anime_works = rsc.import_data(engine, "character_anime_works")
character_nicknames = rsc.import_data(engine, "character_nicknames")
characters = rsc.import_data(engine, "characters")

Successo: Dati letti correttamente.
Successo: Dati letti correttamente.
Successo: Dati letti correttamente.
Successo: Dati letti correttamente.

---

### Checking DataFrames info and visualise first rows

In [2]:
favs.info()
print('\n')
character_anime_works.info()
print('\n')
character_nicknames.info()
print('\n')
characters.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4178743 entries, 0 to 4178742
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   username  object
 1   fav_type  object
 2   id        int64
dtypes: int64(1), object(2)
memory usage: 95.6+ MB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236816 entries, 0 to 236815
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   anime_mal_id      236816 non-null  int64
 1   character_mal_id  236816 non-null  int64
 2   character_name    236816 non-null  object
 3   role              236816 non-null  object
dtypes: int64(2), object(2)
memory usage: 7.2+ MB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36962 entries, 0 to 36961
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   character_mal_id  36962 non-null  int64
 1   nickname          36962 non-null  object
dtypes: int64(1), object(1)
memory usage: 577.7+ KB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   character_mal_id  120 non-null    float64
 1   url               120 non-null    object
 2   name              120 non-null    object
 3   name_kanji        120 non-null    object
 4   image             120 non-null    object
 5   favorites         120 non-null    object
 6   about             120 non-null    object
dtypes: float64(1), object(6)
memory usage: 6.7+ KB

In [3]:
favs

            username   fav_type      id
0          ishikawas      anime   45649
1          ishikawas      anime   38680
2          ishikawas      anime     795
3          ishikawas      anime   37510
4          ishikawas      anime     820
...              ...        ...     ...
4178738  vincent0607  character     497
4178739  vincent0607  character  118739
4178740  vincent0607  character  188177
4178741  vincent0607  character  141354
4178742  vincent0607  character  195178

[4178743 rows x 3 columns]

In [4]:
character_anime_works

        anime_mal_id  character_mal_id    character_name        role
0               2928              5781             Atoli        Main
1               2928                33             Haseo        Main
2               2928                32              Ovan        Main
3               2928                34             Shino        Main
4               2928              5785              Aina  Supporting
...              ...               ...               ...         ...
236811         31245            137157    Shibasaki, Ken  Supporting
236812         36305            136064  Hamanaka, Midori        Main
236813         36305            133916      Narumi, Sena        Main
236814         36305            124942   Hayasaka, Akari  Supporting
236815         34895            155887  Shiraha, Setsuna        Main

[236816 rows x 4 columns]

In [5]:
character_nicknames

       character_mal_id              nickname
0                280205              Hikaruko
1                280129              Hinacchi
2                280127         Bertha Willis
3                280066                 Jimmy
4                280059  Full Body Red Square
...                 ...                   ...
36957            282159             Ling Long
36958            282159            Silvermoon
36959            282227          Mei's Mother
36960            282254                Cyrano
36961            282255                 Lacey

[36962 rows x 2 columns]

In [6]:
characters

,character_mal_id,url,name,name_kanji,image,favorites,about
0,278865.0,https://myanimelist.net/character/278865/Yoshi...,Yoshirou Sonozaki,園崎 義郎,https://cdn.myanimelist.net/images/characters/...,0,The owner of the restaurant Angel Mort.
1,278668.0,https://myanimelist.net/character/278668/Yangyang,Yangyang,秧秧 / ヤンヤン,https://cdn.myanimelist.net/images/characters/...,0,Yangyang journeyed far away from home to becom...
2,277593.0,https://myanimelist.net/character/277593/Louisa,Louisa,ルイサ,https://cdn.myanimelist.net/img/sp/icon/apple-...,0,Louis is a recurring character in the Risou no...
3,277061.0,https://myanimelist.net/character/277061/Eleanor,Eleanor,エレノア,https://cdn.myanimelist.net/img/sp/icon/apple-...,0,Eleanor is a supporting character that appears...
4,276501.0,https://myanimelist.net/character/276501/Jinyang,Jinyang,ジーニャン,https://cdn.myanimelist.net/images/characters/...,0,One of the quadruplets Cao Cao. he sisters are...
...,...,...,...,...,...,...,...
115,281206.0,https://myanimelist.net/character/281206/Hanumon,Hanumon,ハヌモン,https://cdn.myanimelist.net/img/sp/icon/apple-...,0.0,A legendary Beast Man Digimon covered in golde...
116,281717.0,https://myanimelist.net/character/281717/Frank...,Frankenstein,フランケンシュタイン,https://cdn.myanimelist.net/images/characters/...,0.0,A space exploration robot modelled after Frank...
117,281861.0,https://myanimelist.net/character/281861/Machmon,Machmon,マッハモン,https://cdn.myanimelist.net/img/sp/icon/apple-...,0.0,A Cyborg Digimon that yearns for speed. Dust c...
118,282115.0,https://myanimelist.net/character/282115/Cavitt,Cavitt,キャビット,https://cdn.myanimelist.net/images/characters/...,0.0,Lieutenant Rencon's younger sister.\n\nNo voic...
119,282131.0,https://myanimelist.net/character/282131/Lieut...,Lieutenant Rencon,レンコン中尉,https://cdn.myanimelist.net/images/characters/...,0.0,Former lieutenant of Mar Expedition and older ...

### `null` values detection and removal

P.S.: character_anime_works doesn't have null values

In [7]:
favs = favs.dropna(subset=['username'])
favs

            username   fav_type      id
0          ishikawas      anime   45649
1          ishikawas      anime   38680
2          ishikawas      anime     795
3          ishikawas      anime   37510
4          ishikawas      anime     820
...              ...        ...     ...
4178738  vincent0607  character     497
4178739  vincent0607  character  118739
4178740  vincent0607  character  188177
4178741  vincent0607  character  141354
4178742  vincent0607  character  195178

[4178743 rows x 3 columns]

In [8]:
character_nicknames = character_nicknames.dropna(subset=['nickname'])
character_nicknames

       character_mal_id              nickname
0                280205              Hikaruko
1                280129              Hinacchi
2                280127         Bertha Willis
3                280066                 Jimmy
4                280059  Full Body Red Square
...                 ...                   ...
36957            282159             Ling Long
36958            282159            Silvermoon
36959            282227          Mei's Mother
36960            282254                Cyrano
36961            282255                 Lacey

[36962 rows x 2 columns]

In [9]:
characters = characters.dropna(subset=['name'])
characters

,character_mal_id,url,name,name_kanji,image,favorites,about
0,278865.0,https://myanimelist.net/character/278865/Yoshi...,Yoshirou Sonozaki,園崎 義郎,https://cdn.myanimelist.net/images/characters/...,0,The owner of the restaurant Angel Mort.
1,278668.0,https://myanimelist.net/character/278668/Yangyang,Yangyang,秧秧 / ヤンヤン,https://cdn.myanimelist.net/images/characters/...,0,Yangyang journeyed far away from home to becom...
2,277593.0,https://myanimelist.net/character/277593/Louisa,Louisa,ルイサ,https://cdn.myanimelist.net/img/sp/icon/apple-...,0,Louis is a recurring character in the Risou no...
3,277061.0,https://myanimelist.net/character/277061/Eleanor,Eleanor,エレノア,https://cdn.myanimelist.net/img/sp/icon/apple-...,0,Eleanor is a supporting character that appears...
4,276501.0,https://myanimelist.net/character/276501/Jinyang,Jinyang,ジーニャン,https://cdn.myanimelist.net/images/characters/...,0,One of the quadruplets Cao Cao. he sisters are...
...,...,...,...,...,...,...,...
115,281206.0,https://myanimelist.net/character/281206/Hanumon,Hanumon,ハヌモン,https://cdn.myanimelist.net/img/sp/icon/apple-...,0.0,A legendary Beast Man Digimon covered in golde...
116,281717.0,https://myanimelist.net/character/281717/Frank...,Frankenstein,フランケンシュタイン,https://cdn.myanimelist.net/images/characters/...,0.0,A space exploration robot modelled after Frank...
117,281861.0,https://myanimelist.net/character/281861/Machmon,Machmon,マッハモン,https://cdn.myanimelist.net/img/sp/icon/apple-...,0.0,A Cyborg Digimon that yearns for speed. Dust c...
118,282115.0,https://myanimelist.net/character/282115/Cavitt,Cavitt,キャビット,https://cdn.myanimelist.net/images/characters/...,0.0,Lieutenant Rencon's younger sister.\n\nNo voic...
119,282131.0,https://myanimelist.net/character/282131/Lieut...,Lieutenant Rencon,レンコン中尉,https://cdn.myanimelist.net/images/characters/...,0.0,Former lieutenant of Mar Expedition and older ...

### Duplicate rows detection and removal

In [10]:
print(f"Number of rows duplicated (favs): {favs.duplicated().sum()}\n")
print(f"Number of rows duplicated (character_anime_works): {character_anime_works.duplicated().sum()}\n")
print(f"Number of rows duplicated (character_nicknames): {character_nicknames.duplicated().sum()}\n")
print(f"Number of rows duplicated (characters): {characters.duplicated().sum()}")

Number of rows duplicated (favs): 0

Number of rows duplicated (character_anime_works): 0

Number of rows duplicated (character_nicknames): 0

Number of rows duplicated (characters): 0

In [11]:
duplicati = characters[characters.duplicated(keep=False)]
duplicati

Empty DataFrame
Columns: [character_mal_id, url, name, name_kanji, image, favorites, about]
Index: []

In [12]:
favs = favs.drop_duplicates(keep="first")
character_anime_works = character_anime_works.drop_duplicates(keep="first")
character_nicknames = character_nicknames.drop_duplicates(keep="first")
characters = characters.drop_duplicates(keep="first")

In [13]:
print(f"Number of rows duplicated (favs): {favs.duplicated().sum()}\n")
print(f"Number of rows duplicated (character_anime_works): {character_anime_works.duplicated().sum()}\n")
print(f"Number of rows duplicated (character_nicknames): {character_nicknames.duplicated().sum()}\n")
print(f"Number of rows duplicated (characters): {characters.duplicated().sum()}")

Number of rows duplicated (favs): 0

Number of rows duplicated (character_anime_works): 0

Number of rows duplicated (character_nicknames): 0

Number of rows duplicated (characters): 0

### Typo correction

In [14]:
favs.dtypes

username    object
fav_type    object
id           int64
dtype: object

In [15]:
favs = favs.copy()
characters = characters.copy()

characters.loc[:, 'character_mal_id'] = characters['character_mal_id'].astype('int64')
#characters.loc[:, 'favorites'] = characters['favorites'].astype('int64')

favs.loc[:, 'fav_type'] = favs['fav_type'].astype('category')
character_anime_works.loc[:, 'role'] = character_anime_works['role'].astype('category')

### Saving cleaned data in database

In [16]:
rsc.save_data(favs, 'favs', engine)
rsc.save_data(character_anime_works, 'character_anime_works', engine)
rsc.save_data(character_nicknames, 'character_nicknames', engine)
rsc.save_data(characters, 'characters', engine)

Successo: 4178743 righe caricate nella tabella 'favs'.
Successo: 236816 righe caricate nella tabella 'character_anime_works'.
Successo: 36962 righe caricate nella tabella 'character_nicknames'.
Successo: 120 righe caricate nella tabella 'characters'.